export * from './translation';
export * from './ui-translation'
export * from './service';
export * from './why-item';
export * from './coverage-area';
export * from './gallery-item';
export * from './about-feature';
export * from './nav-link';
export * from './contact-info';